index:
    path: /
    controller: App\Controller\HomePageController::index
addGift:
    path: /addGift
    controller: App\Controller\Admin\CatalogController::addGift
show:
    path: /show
    controller: App\Controller\CatalogController::show
quiz:
    path: /quiz
    controller: App\Controller\QuizController::quiz
result:
    path: /result
    controller: App\Controller\QuizController::result
lucky:
    path: /lucky
    controller: App\Controller\QuizController::lucky
category:
    path: /category/{categoryName}
    controller: App\Controller\CatalogController::category
gift:
    path: /gift/{id}
    controller: App\Controller\CatalogController::gift
success:
    path: /success
    controller: App\Controller\HomeController::success